version: "3.0"
services:
  dynamodb-egress:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "dynamodb-egress"
      MODULE_TYPE: "Output"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      AWS_ACCESS_KEY_ID: ABCDEFGHIJ123456
      AWS_SECRET_ACCESS_KEY: ABCDEFGHIJKLMN/()./1234567/ABCDEF
      REGION: us-east-2
      TABLE: TestingModule
    ports:
      - 80:80
